-- CREATE TABLE IF NOT EXISTS CLIENTES(
--     ID INTEGER PRIMARY KEY AUTOINCREMENT,
--     NOMBRE TEXT,
--     APELLIDO TEXT,
--     EMAIL TEXT,
--     EDAD INTEGER,
--     NUMERO_COMPRAS INTEGER
-- )

-- INSERT INTO CLIENTES(NOMBRE, APELLIDO, EMAIL, EDAD, NUMERO_COMPRAS) VALUES
-- ('LUIS', 'JIMENEZ', 'l@l.com', NULL, 12),
-- ('MARIA', 'NUÑEZ', 'm@m.com', 25, NULL)

SELECT * FROM CLIENTES WHERE NUMERO_COMPRAS IS NULL