-- CREATE TABLE USUARIOSX(
-- ID TEXT (2) PRIMARY KEY,
-- NOMBRE TEXT (50),
-- APELLIDO TEXT (50),
-- EDAD INTEGER (2),
-- EMAIL TEXT (50)
-- )
-- INSERT INTO USUARIOSX VALUES
-- ('01', 'JUAN', 'PEREZ', 25, 'j@j.com'),
-- ('02', 'DANIEL', 'GONZALEZ', 16, 'd@d.com'),
-- ('03', 'PEREZ', 'DANIEL', 18, 'p@p.com'),
-- ('04', 'DANIEL', 'PEREZ', 45, 'd@d.com'),
-- ('05', 'ESTEVE', 'GINES', 32, 'e@d.com')

-- CREATE TABLE COMPRAS (
-- ID TEXT (2) PRIMARY KEY,
-- ARTICULO TEXT (50)
-- );
-- INSERT INTO COMPRAS VALUES
-- ('01', 'COMPUTADORA'),
-- ('02', 'TELEVISOR'),
-- ('03', 'CAMA'),
-- ('04', 'SILLA'),
-- ('05', 'MESA')

-- SELECT COMPRAS.*, USUARIOSX.EMAIL FROM COMPRAS JOIN USUARIOSX ON COMPRAS.ID = USUARIOSX.ID
-- SELECT COMPRAS.*, USUARIOSX.EMAIL FROM COMPRAS JOIN USUARIOSX ON COMPRAS.ID = USUARIOSX.ID JOIN CLIENTES ON USUARIOSX.EMAIL = USUARIOSX.EMAIL

-- SELECT ID AS 'LLAVE', CORREO AS 'CORREO ELECTRONICO' FROM CLIENTES
-- INSERT INTO COMPRAS VALUES
-- ('06', 'CAMA')

-- SELECT USUARIOSX.ID, USUARIOSX.APELLIDO,USUARIOSX.EMAIL FROM COMPRAS JOIN USUARIOSX ON COMPRAS.ID = USUARIOSX.ID WHERE ARTICULO = 'CAMA'

-- SELECT USUARIOSX.ID, USUARIOSX.APELLIDO,USUARIOSX.EMAIL FROM COMPRAS JOIN USUARIOSX ON COMPRAS.ID = USUARIOSX.ID WHERE ARTICULO = 'CAMA' OR USUARIOSX.EMAIL = 'j@j.com'

-- ALTER TABLE COMPRAS ADD COLUMN CANTIDAD INTEGER

-- UPDATE COMPRAS SET CANTIDAD = 3 WHERE ID = '04';

-- CREATE TABLE IF NOT EXISTS COMPRASESHOP(
--     ID TEXT PRIMARY KEY,
--     ARTICULO TEXT,
--     CANTIDAD INTEGER
-- )

-- INSERT INTO COMPRASESHOP (ID, ARTICULO, CANTIDAD) VALUES
-- ('01', 'COMPUTADORA', 2),
-- ('02', 'XBOX',3),
-- ('03', 'PS5', 2),
-- ('04', 'PLAY1',5),
-- ('05', 'IPODS',1),
-- ('06', 'DIADEMA', 4)

-- SELECT ID FROM COMPRAS UNION ALL SELECT ID FROM COMPRASESHOP



-- SELECT ID FROM COMPRAS EXCEPT SELECT ID FROM COMPRASESHOP

-- SELECT C.ID, C.EMAIL FROM USUARIOSX C JOIN(SELECT ID FROM COMPRAS EXCEPT SELECT ID FROM COMPRASESHOP) C2 ON C.ID = C2.ID

SELECT C.* FROM USUARIOSX C JOIN(SELECT ID FROM COMPRAS EXCEPT SELECT ID FROM COMPRASESHOP) C2 ON C.ID = C2.ID
